import { Product } from "./types/Product";

export const sampleProducts: Product[] = [
  {
    name: "Nike slim shirt",
    slug: "nike-slim-shirt",
    category: "Shirts",
    image: "../public/images/p2.jpg",
    price: 120,
    countInStock: 10,
    brand: "Nike",
    rating: 4.5,
    numReviews: 10,
    description: "high quality shirt",
  },
  {
    name: "Adidas fit shirt",
    slug: "adidas-fit-shirt",
    category: "Shirts",
    image: "../public/images/p3.jpg",
    price: 100,
    countInStock: 10,
    brand: "Adidas",
    rating: 4.0,
    numReviews: 10,
    description: "high quality shirt",
  },
  {
    name: "Lacoste fit pants",
    slug: "adidas-fit-pants",
    category: "Pants",
    image: "../public/images/p1.jpg",
    price: 220,
    countInStock: 10,
    brand: "Adidas ",
    rating: 4.8,
    numReviews: 17,
    description: "high quality product",
  },
];
